### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
```
42414 INFO DEBUG - + rbenv install --skip-existing 2.3.8
42414 INFO INFO - Installing Ruby-2.3.8
42414 INFO DEBUG - + ynh_exit_properly
```

I just love how there is absolutely zero fucking clue about why this fails, even if the detailed log, like, nothing

**Comment by alexAubin** [comment]
!testme

**Pull request merged**
